sources:

  - name: gz_raw_data
    tables:
      - name: sales
        identifier: aw_gz_sales
        description: |
          Sales data for Greenweez, with one row per product sold in each order.
        columns:
          - name:  date_date  
            description: |
             The date when the purchase was made. The format is YYYY-MM-DD.
          - name: orders_id
            description: |
             Unique identifier for each order. 
          - name: products_id
            description: Unique identifier for each product in the inventory. 
          - name: revenue
            description: Total sale amount for the given product (price_per_unit * quantity_sold).
          - name: quantity
            description: The number of units of the product sold in the specific transaction.
       # tests:
       #   - unique:
       #       column_name: "(orders_id , products_id)"
              
              
      - name: product
        identifier: raw_gz_product
        description: 
          This table contains information about products, including unique product codes and their corresponding prices.
        columns:
          - name: products_id
            description: A unique identifier for each product in the system. This code is used to track and manage inventory.
            tests:
              - unique  
              - not_null  
          - name: purchase_price
            description: The price of the product.
      - name: ship
        identifier: raw_gz_ship
        description: |
          This table contains information related to shipping details for customer orders, including shipping costs and related fees.
        columns:
          - name: orders_id
            description: A unique identifier for each order.
            tests:
              - unique  
              - not_null  
          - name: shipping_fee
            description: The fee charged for shipping the order. 
            tests:
              - not_null
          - name: logcost
            description: Logistical cost associated with the shipping process.
          - name: ship_cost
            description: The shipping cost.
      - name: adwords
        identifier: raw_gz_adwords
      - name: bing
        identifier: raw_gz_bing
      - name: criteo
        identifier: raw_gz_criteo
      - name: facebook
        identifier: raw_gz_facebook
models:
  - name: int_orders_margin
    description: This model aggregates order data by `orders_id`, calculating the total revenue, total quantity, total purchase costs, and margin for each order.
    columns:
      - name: orders_id
        description: Unique identifier for each order. This is used to group the sales data.
        tests:
          - unique
          - not_null
      - name: date_date
        description: The date when the order was placed. Each order has a single corresponding date.
      - name: total_revenue
        description: The total revenue for the order, calculated as the sum of the revenue for each product in the order.
      - name: total_qty
        description: The total quantity of items in the order.
      - name: total_purchase_costs
        description: The total purchase costs for the order, calculated as the sum of purchase costs for each product.
      - name: total_margin
        description: The margin for the order, calculated as the difference between revenue and purchase costs.

  - name: int_orders_operational
    description: This model calculates the operational margin for each order. It includes information from `int_orders_margin` and operational cost details from the `ship` table.
    columns:
      - name: orders_id
        description: Unique identifier for each order. Used to link with other data tables like `int_orders_margin` and `ship`.
        tests:
          - unique
          - not_null
      - name: date_date
        description: The date when the order was placed. This is the same date as in the `int_orders_margin` model.
      - name: total_revenue
        description: The total revenue for the order.
      - name: total_qty
        description: The total quantity of items in the order.
      - name: total_purchase_costs
        description: The total purchase costs for the order.
      - name: total_margin
        description: The margin for the order, previously calculated in the `int_orders_margin` model.
      - name: shipping_fee
        description: The cost of shipping for the order, obtained from the `ship` table.
      - name: logcost
        description: The logistics cost for the order, obtained from the `ship` table.
      - name: ship_cost
        description: The shipping cost for the order, obtained from the `ship` table.
      - name: operational_margin
        description: The operational margin, calculated as `margin + shipping_fee - logcost - ship_cost`.

  - name: int_sales_margin
    description: This model calculates the margin for each product sold within an order. It includes revenue, quantity, purchase costs, and margin details for each product.
    columns:
      - name: orders_id
        description: Unique identifier for each order. This is the same identifier as in the `int_orders_margin` model.
        tests:
          - not_null
      - name: products_id
        description: Unique identifier for each product in the inventory. This links each sale to a specific product.
        tests:
          - not_null
      - name: date_date
        description: The date when the purchase was made, associated with the `orders_id`.
      - name: revenue
        description: The revenue from the sale of the product, calculated as `price_per_unit * quantity_sold`.
      - name: qty
        description: The quantity of the product sold in the specific transaction.
      - name: purchase_price
        description: The price at which the product was purchased, taken from the `products` table.
      - name: purchase_costs
        description: The total cost for the product in the sale, calculated as `quantity * purchase_price`.
      - name: margin
        description: The margin for the product, calculated as `revenue - purchase_costs`.

  - name: finance_days
    description: This model aggregates financial data on a daily basis. It includes total revenue, quantity, number of transactions, margin, and operational margin per day.
    columns:
      - name: date_date
        description: The date of the financial data aggregation.
        tests:
          - not_null
      - name: total_revenue
        description: The total revenue for the day, aggregated across all orders.
      - name: total_qty
        description: The total quantity of products sold on the day.
      - name: nb_transaction
        description: The number of unique transactions (orders) that occurred on the given date.
      - name: total_margin
        description: The total margin for the day, calculated as the sum of margins for all orders.
      - name: operational_margin
        description: The total operational margin for the day, calculated as the sum of operational margins for all orders.
      - name: total_purchase_costs
        description: The total purchase costs for the day, calculated as the sum of costs across all orders.
      - name: total_shipping_fees
        description: The total shipping fees for the day, calculated as the sum of shipping fees for all orders.
      - name: total_logcosts
        description: The total logistics costs for the day, calculated as the sum of logistics costs for all orders.
      - name: avg_basket
        description: The average basket size (total revenue divided by the number of distinct orders) for the day.
  - name: int_campaigns
    description: "This model aggregates campaign data from multiple staging tables into a single intermediate model, including campaign performance metrics like cost, impressions, and clicks."
    columns:
      - name: date_date
        description: "Date of the campaign data."
        tests:
          - not_null

      - name: paid_source
        description: "Source from which the paid campaign originated (e.g., Google, Facebook, etc.)."
        tests:
          - not_null

      - name: campaign_key
        description: "Unique key that identifies the campaign."
        tests:
          - not_null

      - name: campaign_name
        description: "Name of the campaign (renamed from 'campgn_name' for consistency)."
        tests:
          - not_null

      - name: ads_cost
        description: "Cost of the campaign's ads (cast to float64)."
        tests:
          - not_null

      - name: impression
        description: "Number of impressions for the campaign."
        tests:
          - not_null

      - name: click
        description: "Number of clicks generated from the campaign."
        tests:
          - not_null

    # Primary key defined as a combination of `date_date` and `campaign_key`
    #tests:
    #  - unique:
    #      columns: ['date_date', 'campaign_key']
  - name: int_campaigns_day
    description: aggregated version of int_campaigns model for each day
    columns:
      - name: date_date
        description: date, primary key
        tests:
          - unique
      - name: ads_cost
        description: agregated ads_costs
        tests:
          - not_null
      - name: ads_impressions
        description: agregated impressions per day
        tests:
          - not_null              
      - name: ads_clicks
        description: agregated number of clicks per day
        tests:
          - not_null
          
              